# Generated by Django 3.1.1 on 2020-12-17 13:45

from django.db import migrations, models
import posts.validators


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_report_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='video',
            field=models.FileField(null=True, upload_to='', validators=[posts.validators.validate_file]),
        ),
    ]
