# Generated by Django 3.1.1 on 2020-12-18 18:33

from django.db import migrations, models
import posts.validators


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_auto_20201218_1829'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(default=None, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='post',
            name='video',
            field=models.FileField(default=None, null=True, upload_to='', validators=[posts.validators.validate_file]),
        ),
    ]
